# Generated by Django 4.2.7 on 2023-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="Фото URL"),
        ),
    ]
